

FAIL back() and forward() out of bounds assert_equals: committed and finished must reject with the same value expected object "InvalidStateError: Cannot go back" but got object "InvalidStateError: Cannot go back"

